### ISSUE TITLE
How can i change NODE_PATH to /src

### ISSUE THREAD

**Issue by thanhpd56** [kriasoft/nodejs-api-starter#100]
I add `NODE_PATH=src/` into .env but, there is no effect. How can i change node path folder?

**Comment by koistya** [comment]
The environment variables are currently bing set via [`docker-compose.yml`](https://github.com/kriasoft/nodejs-api-starter/blob/462df55/docker-compose.yml)

**Comment by thanhpd56** [comment]
@koistya I try to add `- NODE_PATH=src/` into environment of docker-compose.yml, but it does not work.

> Error: Cannot find module 'routes/authenticated-router'.
Any suggestion?
