### ISSUE TITLE
Copies files with corruption

### ISSUE THREAD

**Issue by Khangeldy** [kriasoft/nodejs-api-starter#104]
I have some problem with fonts and images in my project. The build script copies images from public folder, but they not visible in browser. If i manually copy them in build folder everything works as should. What is wrong? Images causes problem except svg files. And about fonts. Browser can see them. But i have warnings in my console
```
Failed to decode downloaded font: <URL>
OTS parsing error: incorrect file size in WOFF header
OTS parsing error: GPOS: misaligned table
```
Maybe there something not correct in tools/build.js ?
```
              } else if (src.startsWith('src')) {
                const data = fs.readFileSync(src, 'utf8');
                fs.writeFileSync(dest, data, 'utf8');
                console.log(src, '->', dest);
              }
```

**Comment by Khangeldy** [comment]
I am using just plain scripts without docker

**Comment by cmmartin** [comment]
@Khangeldy Seems unlikely the issue is caused by copying to build. Can you generate a hash of the file in your app folder compared to the one in build and see if they are different?

**Comment by Khangeldy** [comment]
@cmmartin Ok I should try
