### ISSUE TITLE
Live Reload Not Working

### ISSUE THREAD

**Issue by ajainvivek** [kriasoft/nodejs-api-starter#18]
Hi,

Live Reload not working on MacOs 

Volume mounting is working fine and the changes are getting copied over.

**Comment by koistya** [comment]
Hi, Ajain. I'm unable to reproduce this issue. Are you running the latest version of [Docker for Mac](https://docs.docker.com/docker-for-mac/)?

**Comment by bwoodlt** [comment]
Hi. Seems to work for me. Not having issues with Live Reload on MacOSx.

**Comment by koistya** [comment]
@ajainvivek ah, maybe you expecting it to reload the browser? But this project doesn't have any front-end code, nothing to reload in a browser, it just restarts Node.js app server once code changes are detected.

**Comment by ajainvivek** [comment]
I am running Docker version 1.12.2, build bb80604 but I can see the files getting changed over the docker container but the node server doesn't restart. I have made changes to users.js. 

watch mode is also set to true.

```
watcher.on('all', (event, src) => {
    console.log('file changed......');
    // Reload the app if .env or package.json file has changed (in watch mode)
    if (src === '.env' || src === 'package.json' || src === 'yarn.lock') {
      if (ready && onComplete) onComplete();
      return;
    }
```

chokidar doesn't capture file changes event after build. the log doesn't print after build

**Comment by ajainvivek** [comment]
I have also upgraded docker on the docker-machine instance but the file changes where never triggered. 

After enabling polling. It works.

`usePolling: true`

I have other projects which uses **nodemon** which requires legacyWatch enabled to make it work on docker.

I am curious to know what would be the potential cause.

**Comment by koistya** [comment]
@ajainvivek it should work without setting `usePolling: true`. Can you check `docker --version`?

**Comment by ajainvivek** [comment]
Sorry for the late response the docker version .. I was running was Docker version 1.12.2, build bb80604

**Comment by koistya** [comment]
@ajainvivek I'm still unable to reproduce the issue. Maybe you can try the latest Docker version - v17.03.0 Community Edition

**Comment by koistya** [comment]
In order to make the file watcher use "polling", create `docker-compose.override.yml` file in the root directory of your project with the following content:

```
version: '3'
services:
  api:
    environment:
      - CHOKIDAR_USEPOLLING=true
```
