### ISSUE TITLE
Why in read-only mode for databases?

### ISSUE THREAD

**Issue by VikramTiwari** [kriasoft/nodejs-api-starter#24]
If the databases are read-only, how do you suppose even the init scripts to work? Even on production, why would you have your databases read-only?

**Comment by Falieson** [comment]
This solved the issue I was going to open, maybe an explanation in the readme would be sufficient?

```api_1       | Finished 'build' after 931ms
api_1       | Node.js API server is listening on http://localhost:5000/
postgres_1  | chown: /var/run/postgresql: Read-only file system
postgres_1  | chown: /var/run/postgresql: Read-only file system
postgres_1  | chown: /var/run/postgresql: Read-only file system
postgres_1  | chown: /var/run/postgresql: Read-only file system
```

**Comment by gihrig** [comment]
Seems like a bug? #25 fixed it.

**Comment by koistya** [comment]
@Falieson wouldn't it be better to add `/run/postgresql` to [tmpfs](https://github.com/kriasoft/nodejs-api-starter/blob/27724a4/docker-compose.yml#L28)?

**Comment by koistya** [comment]
@VikramTiwari, @Falieson, @gihrig FYI, the reason why there is `read_only: true` flag is that this way the `docker-compose.yml` file looks similar to what would likely be used in a production environment.
