### ISSUE TITLE
Optimize Babel configuration for Node.js v7.7+

### ISSUE THREAD

**Issue by koistya** [kriasoft/nodejs-api-starter#27]
For example, Node.js v7.7 supports async/await natively, need to remove related plugins from the list. See [`.babelrc`](https://github.com/kriasoft/nodejs-api-starter/blob/master/.babelrc).

**Comment by frenzzy** [comment]
Or even better start using [babel-preset-env](https://github.com/babel/babel-preset-env) instead.
