### ISSUE TITLE
Adding example integration tests

### ISSUE THREAD

**Issue by TheHollidayInn** [kriasoft/nodejs-api-starter#29]
I see that unit tests are included, but I think adding some sample integration tests would also be helpful. Which could include using something like super test to send route requests.

**Comment by koistya** [comment]
@TheHollidayInn there is an integration test example here [`test/unit/types.ViewerType.spec.js`](https://github.com/kriasoft/nodejs-api-starter/blob/master/test/unit/types.ViewerType.spec.js). Maybe we should move that into another folder?

**Comment by koistya** [comment]
@TheHollidayInn thanks for the suggestion. Unfortunately, it was open for too long. Feel free to reopen.
