### ISSUE TITLE
Authentication and authorization

### ISSUE THREAD

**Issue by koistya** [kriasoft/nodejs-api-starter#3]
- [x] Create database schema for user accounts, logins and authentication tokens
- [x] Create tooling for database migrations
- [x] Add Facebook authentication strategy
- [x] Add Google authentication strategy
- [x] Add Twitter authentication strategy
- [x] Add `/login/:provider/:returnURL?` and `/login/:provider/return` routes
- [x] Support relative and external "return URL", e.g. https://reactstarter.com/login/facebook/http://localhost:3000/
- [x] Add `/logout/:returnURL?` route

Ref http://passportjs.org/

**Comment by linonetwo** [comment]
Accessing https://graphql-demo.kriasoft.com/login/facebook/return?code= thows ```Cannot GET /login/facebook/return```
