### ISSUE TITLE
Add "Local" authentication strategy

### ISSUE THREAD

**Issue by koistya** [kriasoft/nodejs-api-starter#30]
We need to support the scenario when a website user can click [Sign In], enter his or her email address, click [Next].. The server must send an email with a temporary pass code and/or URL link; user clicks on the link or enters the code on the next screen of the login page and thus authenticates himself (no need to remember a password).

The list of [Passport.js](http://passportjs.org/) authentication strategies can be found in `src/passport.js` and the list of login options such as `www.example.com/login/facebook` is located in `src/routes/account.js`.

**Comment by followbl** [comment]
@koistya I'd like to help and add this to the kit. 

I understand you'd like to add the magic password/link authentication...but do you also want to add this? https://github.com/jaredhanson/passport-local like the ticket mentions "local"? 

Happy to add one or both. Thanks for the awesome repo

**Comment by koistya** [comment]
It might be easier to integrate an existing auth provider, e.g. Google Auth Toolkit / Firebase Auth etc.
