### ISSUE TITLE
Create an index on user.emails column in the database

### ISSUE THREAD

**Issue by koistya** [kriasoft/nodejs-api-starter#36]
File to edit [`migrations/201612010000_initial.js`](https://github.com/kriasoft/nodejs-api-starter/blob/f0e1678/migrations/201612010000_initial.js#L21)

#### References
https://www.postgresql.org/docs/current/static/datatype-json.html#JSON-INDEXING
http://knexjs.org/#Schema-index

**Comment by rajpatel507** [comment]
Can i work on this?

**Comment by koistya** [comment]
@rajpatel507 sure, that would be awesome!

**Comment by rajpatel507** [comment]
@koistya I am new to lnexjs and postgresql but what i understand from my limited knowledge that

`table.jsonb('emails').notNullable().defaultTo('[]').index();`

will work right?

**Comment by koistya** [comment]
@rajpatel507 I just removed plural `emails` field in favor of a single `email` field in order to simplify things a little.
