### ISSUE TITLE
Integrate Prettier

### ISSUE THREAD

**Issue by koistya** [kriasoft/nodejs-api-starter#41]
https://prettier.github.io/prettier/

**Comment by pruhstal** [comment]
Wouldn't it make more sense to enforce code styling with some eslint rules and not accept anything that doesn't pass a pre-commit hook into this repo?

Seems like there are more things that would be useful to add to this particular project.

**Comment by cmmartin** [comment]
I personally prefer `prettier` to `eslint`, although they could, and possibly should, both be used as mentioned in [this tweet](https://twitter.com/slicknet/status/877194938508656641). The prettier docs even include [an example](https://github.com/prettier/prettier#eslint) of using it alongside`eslint`.

Usually prettier is implemented in your IDE. I'd imagine integrating here would just amount to running the current code through prettier and adding a pre-commit hook [like this](https://github.com/prettier/prettier#pre-commit-hook)

**Comment by followbl** [comment]
@koistya close this one?

**Comment by koistya** [comment]
@followbl yep, thanks for heads up!
