### ISSUE TITLE
ERROR:  function uuid_generate_v1mc() does not exist

### ISSUE THREAD

**Issue by kraftpixel** [kriasoft/nodejs-api-starter#45]
Host OS : Windows 10
Solution was to connect to PostgreSQL and execute the following but I'm not too familiar with Docker to run it automatically while compose up.

CREATE EXTENSION "uuid-ossp";

**Comment by koistya** [comment]
Take a look here: https://github.com/kriasoft/nodejs-api-starter/blob/master/config/postgres-initdb.sh#L8

**Comment by kraftpixel** [comment]
I think it was due to missing entries in the hosts file.

After fixing those to my hosts file manually I did the following to try and recreate the database and it worked
`docker-compose down`
`docker-compose up`

Does docker add the entries to hosts file automatically?

Errors I noticed
```
api_1    | Node.js API server is listening on http://api:8080/
api_1    |   Error: getaddrinfo ENOTFOUND db db:5432
```

```
api_1    | Starting 'run'...
api_1    | Starting 'db-migrate'...
db_1     | FATAL:  database "dev" does not exist
db_1     | FATAL:  database "dev" does not exist
db_1     | FATAL:  database "dev" does not exist
api_1    | error: database "dev" does not exist
api_1    |     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:567:11)
api_1    |     at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:391:17)
api_1    |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:129:22)
api_1    |     at emitOne (events.js:115:13)
api_1    |     at Socket.emit (events.js:210:7)
api_1    |     at addChunk (_stream_readable.js:252:12)
api_1    |     at readableAddChunk (_stream_readable.js:239:11)
api_1    |     at Socket.Readable.push (_stream_readable.js:197:10)
api_1    |     at TCP.onread (net.js:588:20)
```

**Comment by kraftpixel** [comment]
I tried installing it on a new system today and got this error.
/docker-entrypoint-initdb.d/initdb.sh: line 2: $'\r': command not found

**Comment by koistya** [comment]
Just to be clear, are we talking about running the app on a dev machine, or you're trying to deploy it? The `docker-compose.yml` in this project is intended to be used in a development environment.

**Comment by kraftpixel** [comment]
Yup, that was when trying to run it on a dev machine through docker.

**Comment by koistya** [comment]
One thing to node is that `/docker-entrypoint-initdb.d/initdb.sh` is only executed once when "data" volume is created (run `docker volume ls` to see the list of volumes). If the "dev" database is missing, you can either create it manually or remove the "data" volume and try running "docker compose up" again.

**Comment by koistya** [comment]
I just included `CREATE EXTENSION "uuid-ossp";` into the migration file.
