### ISSUE TITLE
Add Relay compatibility

### ISSUE THREAD

**Issue by koistya** [kriasoft/nodejs-api-starter#5]
http://facebook.github.io/relay/

**Comment by HarrisRobin** [comment]
@koistya awesome repo here! I just have a question, until you add Relay compatibility, does this mean that this repo won't support `pageInfo` fields such as `totalCount`?

**Comment by koistya** [comment]
@HarrisRobin That's correct. It should be easy to add `relay` though I believe, it won't conflict with the existing code as most of it related to developer experience - build and run the app with "live reload" inside Docker, authentication with Passport.js etc.
