### ISSUE TITLE
Would you consider creating this but without docker?

### ISSUE THREAD

**Issue by psyanite** [kriasoft/nodejs-api-starter#74]
I see a lot of people have had trouble setting up docker especially those who have Windows machines, is it possible to create a similar repository but without the docker component, even if it is not updated regularly I think it would still be extremely beneficial.

Cheers! 🌮

**Comment by DaveyEdwards** [comment]
I am not sure about them creating it without Docker, but I to ran into issues getting it working with Windows.  I got some help from Koistya and then made a video/article for setting it up: (if you still have troubles)

Video: https://www.youtube.com/watch?v=IV4IsYyfdKI&feature=youtu.be
Written guide: https://medium.com/@daveyedwards/how-to-setup-kriasofts-nodejs-api-starter-on-windows-10-a092d6e34882

**Comment by psyanite** [comment]
@DaveyEdwards Hi davey, thanks for your reply, those are the steps I have followed but I have encountered many issues since and is talking to @koistya about it in another thread. Maybe I'll check out the Youtube video and see if I have missed anything.

Thank you! :+1:
