### ISSUE TITLE
Replace Passport.js authentication with Firebase auth

### ISSUE THREAD

**Issue by koistya** [kriasoft/nodejs-api-starter#76]
What do you think about replacing Passport.js/session-based authentication with [Firebase authentication](https://firebase.google.com/products/auth/), which already supports phone verifications - 10K/month for free, password reset etc.

**Comment by hieuhani** [comment]
Sounds good but in term of starter kit we may need to cover the most basic cases and Passport.js is still good enough and independent.
But actually Firebase Authentication helps us to save a lot of time, what do you think if we develop the starter kit to support installable addons, plugins? Users only need to choose the proper addons to use and it will help them a lot to create a Minimum Viable Product.

**Comment by DaveyEdwards** [comment]
I think for the majority of people this would be the best option (Disclaimer I have never actually used Firebase).  As soon as people using this stop keeping up with master and letting their auth start to slide (or change things in it) they may have security problems.  If that can be extracted for a fully managed solution + with a very generous free tier + extra capabilities is a very good route.  The people who are wanting to build their own custom auth I am guessing would be building their own anyway (maybe keep an example or branch for setting up auth the way it is).

Once connected it would also help those that want to extend their application and start hooking into other Firebase features.   I personally can't see any negatives to this and am wondering if anyone has any?

**Comment by koistya** [comment]
You can find authentication example here https://github.com/kriasoft/nodejs-api-starter/issues/129#issuecomment-664372960
