### ISSUE TITLE
Running yarn docker-test does not work

### ISSUE THREAD

**Issue by AdamZaczek** [kriasoft/nodejs-api-starter#82]
Hi, I'm very happy with this repo and the way it has built-in docker based architecture which I'm learning atm. I got such error today:

Error message:
```
Starting nodejsapistarter_redis_1 ... done
Starting nodejsapistarter_db_1 ... done
yarn run v1.3.2                                                                
$ jest                                                                         
/bin/sh: jest: not found
error Command failed with exit code 127.
```

Steps to reproduce:

1. Clone the repo
2. Run yarn docker-test

I can make a pull request fixing this.

**Comment by koistya** [comment]
If your unit tests don't require a database connection, you can run them without docker:

```bash
yarn test       # or, yarn test --watch
```

Alternatively, you can launch your app, connect to the API container and run `yarn test` from inside the container:

```bash
my-app $ docker-compose up -d
my-app $ docker-compose exec api sh
/usr/src/bin $ yarn test
```
