### ISSUE TITLE
ERROR: for backendapp_api_1  Cannot start service api: driver failed programming external connectivity on endpoint backendapp_api_1: Error starting userland proxy: Bind for 127.0.0.1:9229 failed: port is already allocated

### ISSUE THREAD

**Issue by adamchenwei** [kriasoft/nodejs-api-starter#85]
when I did `docker-compose up` inside the app root directory. this is what I got

![screen shot 2018-01-04 at 1 46 36 pm](https://user-images.githubusercontent.com/4201698/34579147-c9268690-f155-11e7-9e34-b4206e5b2e96.png)

Any idea why is this happening?
*Note: I removed all containers

**Comment by koistya** [comment]
You can try to comment out these two lines: https://github.com/kriasoft/nodejs-api-starter/blob/master/docker-compose.yml#L30-L31

They are only used when you launch the app in debug (inspect) mode. It seems like some other app was already launched on this port.
