### ISSUE TITLE
Npm packages not available

### ISSUE THREAD

**Issue by crystal520** [kriasoft/nodejs-api-starter#88]
Due to : 
https://github.com/npm/registry/issues/255

[2/4] Fetching packages...
api_1    | error An unexpected error occurred: "https://registry.yarnpkg.com/require-from-string/-/require-from-string-2.0.1.tgz: Request failed \"404 Not Found\"".
api_1    | info If you think this is a bug, please open a bug report with the information provided in "/usr/src/app/yarn-error.log".
api_1    | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Can we somehow cache it somewhere just in case some packages gone again?

**Comment by frenzzy** [comment]
You can start using your own npm registry as a cache proxy. See [sinopia](https://github.com/rlidwka/sinopia) as one of the way

**Comment by koistya** [comment]
That was a temporary issue with **npm** registry.
