### ISSUE TITLE
Error: Cannot find module 'del'

### ISSUE THREAD

**Issue by kudzuu** [kriasoft/nodejs-api-starter#89]
$ docker-compose up

 Error: Cannot find module 'del'
api_1    |     at Function.Module._resolveFilename (module.js:536:15)
api_1    |     at Function.Module._load (module.js:466:25)
api_1    |     at Module.require (module.js:579:17)
api_1    |     at require (internal/module.js:11:18)
api_1    |     at Object.<anonymous> (/usr/src/app/tools/build.js:11:13)
api_1    |     at Module._compile (module.js:635:30)
api_1    |     at Object.Module._extensions..js (module.js:646:10)
api_1    |     at Module.load (module.js:554:32)
api_1    |     at tryModuleLoad (module.js:497:12)
api_1    |     at Function.Module._load (module.js:489:3)
exampleapi_api_1 exited with code 1

**Comment by brianupskill** [comment]
@kudzuu Currently running into this issue when changing the NODE_ENV to production. How did you proceed?
