### ISSUE TITLE
docker-compose builds as root

### ISSUE THREAD

**Issue by smishr4** [kriasoft/nodejs-api-starter#90]
First, thank you very much for this wonderful node-boilerplate, It really does cover a long tech stack which I am trying to complete bit by bit.

Problem which I encountered when I tried to run this as described, simply did:
`cd nodejs-api-starter`
`docker-compose up`

And I get this error:
`api_1    | EACCES: permission denied, mkdir 'build/emails'`
`api_1    | EACCES: permission denied, mkdir 'build/emails'`
...
and so on.

The problem here is that the build directory created by running build.js through docker-compose is root protected and doesn't allow any further changes, so the build process fails and finally the ./build/server.js is unavailable. I can manually create a build directory that is not root protected and repeat the process then it works. Probably something to do with docker's functioning and my lack of experience in working with it. Can you help me figure out a work around?

screenshot:
http://i.imgur.com/ckiomWY.png

**Comment by shadowbrush** [comment]
Out of the box, Docker on Ubuntu requires root, see: https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

**Comment by smishr4** [comment]
That I fixed when I tried my first docker program. I made a small `express` program, and a simple `Dockerfile`:
# Use latest node image
FROM node:9-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
CMD ["npm", "start" ]
EXPOSE 4000

 and I built image using the following:
`docker build -t node-docker .`
and then ran the image using:
`docker run -p 4000:4000 -v ~/testProjects/node-docker/:/usr/src/app node-docker`

the `source`, `node_modules` and `package.json` everything inside my project directory and I am able to run this without `sudo` after adding the $USER to docker usergroup.

**Comment by Whitematter33** [comment]
@smishr4 On our side, other than running an initial `mkdir build` as the account running `docker-compose up`. I don't know another way around it. The interesting thing is that this only happens for me on my ubuntu server, not on my local macOS. would be curious as to why that initial folder creation is run under root context.

**Comment by smishr4** [comment]
I think probably something to do the way docker creates the directory on linux machine.
https://github.com/docker/compose/issues/2781#issuecomment-176791391

https://stackoverflow.com/questions/33509752/docker-compose-creates-file-owned-by-root

Anyways instead of doing `mkdir build` the neater solution would be to just give the permission using `chown`

Doing this works too:

`sudo chown -R $USER:$USER .`
`docker-compose up`

Thanks
Since this is problem with the way docker is working on ubuntu, you can close this issue and create a reference. Again its a great project and I am kinda struggling with graphql-relay as I have only learned graphql just recently using express-graphql with graphiql interface to write queries, if you can suggest me a good place to start from, that would be a good help.

**Comment by cmmartin** [comment]
@koistya Isn't this happening because in production, ownership of the build folder is not switched to the `node` user in the [Dockerfile](https://github.com/kriasoft/nodejs-api-starter/blob/master/Dockerfile#L17)

This is the relevant section. Notice how in development and test env, we `chown -R node:node build` but not in production...

```
RUN set -ex; \
  if [ "$NODE_ENV" = "production" ]; then \
  yarn install --no-cache --frozen-lockfile --production; \
  elif [ "$NODE_ENV" = "test" ]; then \
  touch yarn-error.log; \
  mkdir -m 777 build; \
  yarn install --no-cache --frozen-lockfile; \
  chown -R node:node build node_modules package.json yarn.lock yarn-error.log; \
  else \
  touch yarn-error.log; \
  mkdir -p -m 777 build node_modules /home/node/.cache/yarn; \
  chown -R node:node build node_modules package.json yarn.lock yarn-error.log /home/node/.cache/yarn; \
  fi;
```

If I step into my api container on Ubuntu in production mode, I can see that all folders are owned by `node:node` except the build folder, which is owned by `root:root`
