### ISSUE TITLE
DigitalOcean: Docker Run / yarn deploy not working?

### ISSUE THREAD

**Issue by quachdev** [kriasoft/nodejs-api-starter#92]
I have setup and deployed an image onto the Docker hub. 

I have a DigitalOcean instance running with docker installed and can pull in the latest image. 

Whenever I run `docker run <repo>` I am getting the error `Cannot find module 'source-map-support'`

Am I supposed to be running the image in a different way?

I tried deploying via `node tools/publish <host>` and received this error as well:

`ERROR: for app_api_1  Cannot start service api: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/usr/src/app/yarn.lock\\\" to rootfs \\\"/var/lib/docker/overlay2/6e6c2ca99741b1caee00123a6b30955444eb086996fca30456cb2bdeabf6198f/merged\\\" at \\\"/var/lib/docker/overlay2/6e6c2ca99741b1caee00123a6b30955444eb086996fca30456cb2bdeabf6198f/merged/usr/src/app/yarn.lock\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type`

Edit: When running the deploy tool, it seems to convert the `yarn.lock` file to a directory... Am I missing something here? I took a look at the tools/publish.js file and followed the directions. I don't see anything in there that would generate the files as directories.

Edit2: Just tried deploying with a fresh copy of the project
put the `docker-compose.yml` file in `/usr/src/app` directory like the docks say. Received the same error when running the deploy script

Any help would be great!

**Comment by slawekl** [comment]
I have the same issue on ubuntu server, deploy is from mac.

**Comment by brianupskill** [comment]
@quachdev Were you able to figure out this issue?
