### ISSUE TITLE
Using MySQL instead

### ISSUE THREAD

**Issue by holidaycottages** [kriasoft/nodejs-api-starter#95]
Hi,

Am looking at this boilerplate to use in our new project, I am looking through the code and can see where Postgres is used but was wondering if you could help me use MySQL instead?

**Comment by MooreDevelopment** [comment]
Most likely. They use Knex, which can be used with postgres and MySQL both. It might take some work on your part. It will just be the initialization of the connection that would need to be changed.

**Comment by koistya** [comment]
Just install MySQL driver instead of `pg`, then replace `pg` with `mysql` in the `src/db.ts` file.
